version: "3"
services:
    clickhouse-server:
     image: yandex/clickhouse-server
     ports:
     - "8123:8123"
     - "9000:9000"
     - "9009:9009"
     ulimits:
      nproc: 65535
      nofile:
       soft: 262144
       hard: 262144
    postgres-server:
      image: postgres
      environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=accounting
      ports:
        - "5433:5432"
    tarantool1:
      image: tarantool/tarantool:2.5.1
      environment:
        TARANTOOL_REPLICATION: "tarantool1,tarantool2"
      networks:
       - mynet
      ports:
       - "3301:3301"
    tarantool2:
      image: tarantool/tarantool:2.5.1
      environment:
        TARANTOOL_REPLICATION: "tarantool1,tarantool2"
      networks:
       - mynet
      ports:
       - "3302:3301"
    blueline:
      build: docker/
      networks:
        - mynet
      depends_on:
        - tarantool1
        - tarantool2
networks:
  mynet:
   driver: bridge